### ISSUE TITLE
how to specify auth credentials for my own registry

### ISSUE THREAD

**Issue by Matthijz98** [namshi/roger#61]
Hi,
I love your application but i have one question.
In the documentation you sai you can add a registry.yourowndomain.com but how do i add a username and password for this registry?

I did read the docs 3 times but can not find it or figure it out

**Comment by orbitalmute** [comment]
You need to add this sections:
```
auth:
  registry:
    serveraddress: <registry_address>
    username: <registry_user>
    password: <registry_password>
```
But you will got an error:
`("(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/fnndsc/ubuntu-python3/tags/list: unauthorized: incorrect username or password"}`
This is due to the dockerode library, it tries to use these credentials globally, for the docker hub and for the private repository.
I came up with only one solution - create the same user in docker hub. But it's works :)
